<script setup lang='ts'>
import Input from '@/components/ui/input/Input.vue';
import { Search, Mic, CircleX } from 'lucide-vue-next';
import { ref, watch } from 'vue';
import { city, type ICityItem } from '@/apis/city.ts'
import Card from '@/components/Card.vue';

defineOptions({
    name: 'SearchView'
})

const history = ref([
    {
        name: '家',
        address: '深圳市 梅东五路'
    },
    {
        name: '公司',
        address: '深圳市 罗湖区'
    }
]);
const cityName = ref('')
const curCityObj = ref({})
watch(() => cityName.value, () => {
    curCityObj.value = {}
    let id: string = '0'
    const province: ICityItem = city[0]; // Generated by Copilot
    setTimeout(() => {
        for (const key in province) {
            const item = province[key]
            if (item.search(cityName.value) > -1) {
                id = key
                Object.assign(curCityObj.value, city[id])
            }
        }
    }, 1000)

})
const clear = () => {
    cityName.value = ''
    curCityObj.value = {}
}
</script>
<template>
    <div class="main bg-background h-full relative ">
        <div class="flex p-4">
            <div class="flex-1 relative items-center bg-foreground/40 rounded-lg text-foreground">
                <Input id="search" type="text" placeholder="搜索城市或机场" class="pl-6 text-foreground" v-model="cityName" />
                <span class="absolute start-0 inset-y-0 flex items-center justify-center px-2">
                    <Search class="text-foreground" :size="14" />
                </span>
                <span class="absolute end-0 inset-y-0 flex items-center justify-center px-2">
                    <CircleX class="text-foreground" :size="14" v-if="cityName" @click="clear" />
                    <Mic class="text-foreground" :size="14" v-else />
                </span>
            </div>
            <div class="w-10 text-foreground text-center leading-7" @click="$router.push('/')">取消</div>
        </div>
        <div v-if="!cityName" class="px-4">
            <div class="mt-2 text-muted-foreground text-xs">建议</div>
            <div class="history flex flex-col gap-2 text-foreground text-sm mt-1">
                <div v-for="(item, index) in history" :key="index">
                    <div>{{ item.name }}</div>
                    <div class="text-foreground/80">{{ item.address }}</div>
                </div>
            </div>
        </div>
        <div v-else style="height:calc(100% - 70px)" class="overflow-y-auto border-1 px-4">
            <div class="mt-1 text-foreground" v-for="(value, key) in curCityObj" :key="key">{{ value }}</div>
        </div>
        <Card />
    </div>
</template>