<script setup lang='ts'>
import { getWindDirection } from '@/utils/weather';

defineOptions({
    name: 'WindCom'
})
defineProps([
    'curData'
])
</script>
<template>
    <div class="mt-2 w-full rounded-lg p-2 text-sm  bg-foreground/20">
        <div class="text-xs text-foreground/50 flex flex-row mb-2">
            <Wind color="#ccc" :size="16" />
            <span>风</span>
        </div>
        <div class="text-xs flex justify-between flex-row gap-2">
            <div class="w-3/5">
                <div class="py-2 flex flex-row justify-between border-b-1 border-foreground/50">
                    <span>风力</span>
                    <!-- Generated by Copilot -->
                    <span class="text-foreground/50">{{ curData.wind.gust }}级</span>
                </div>
                <div class="py-2 flex flex-row justify-between border-b-1 border-foreground/50">
                    <span>阵风</span>
                    <span class="text-foreground/50">{{ curData.wind.speed }}米/秒</span>
                </div>
                <div class="py-2 flex flex-row justify-between">
                    <span>方向</span>
                    <span class="text-foreground/50">{{ getWindDirection(curData.wind.deg)
                        }}{{ curData.wind.deg }}°</span>
                </div>
            </div>
            <div>风的图片</div>
        </div>
    </div>
</template>