<script setup lang='ts'>
import { getWindDirection } from '@/utils/weather';
import { Wind } from 'lucide-vue-next';
import { onMounted, nextTick } from 'vue';

defineOptions({
    name: 'WindCom'
})
defineProps([
    'curData'
])

const drawCompass = (
    angle: number,
    speed: number,
    canvas: HTMLCanvasElement,
    ctx: CanvasRenderingContext2D | null
): void => {
    // 清空画布
    ctx!.clearRect(0, 0, canvas!.width, canvas!.height);

    // 绘制圆环
    ctx!.beginPath();
    ctx!.arc(77, 77, 70, 0, Math.PI * 2);
    ctx!.strokeStyle = '#eee';
    ctx!.lineWidth = 1;
    ctx!.stroke();

    // 绘制方向刻度
    ['N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW'].forEach((dir: string, i: number) => {
        const rad: number = (i * 45 - 90) * Math.PI / 180;
        ctx!.fillText(dir, 100 + 60 * Math.cos(rad), 100 + 60 * Math.sin(rad));
    });

    // 绘制箭头（根据风向角度）
    ctx!.save();
    ctx!.translate(100, 100);
    ctx!.rotate(angle * Math.PI / 180);
    ctx!.beginPath();
    ctx!.moveTo(0, -50);
    ctx!.lineTo(-10, -20);
    ctx!.lineTo(0, -30);
    ctx!.lineTo(10, -20);
    ctx!.closePath();
    ctx!.fillStyle = '#f00';
    ctx!.fill();

    // 绘制风级条
    ctx!.fillStyle = '#333';
    ctx!.fillText(`${speed}级`, 0, 30);
    ctx!.restore();
}
onMounted(async () => {
    await nextTick()
    // Generated by Copilot
    const canvas: HTMLCanvasElement | null = document.getElementById('wind-canvas') as HTMLCanvasElement | null;
    const ctx = canvas!.getContext('2d');
    // 使用示例
    if (canvas) drawCompass(45, 3, canvas, ctx); // 东北风3级
})
</script>
<template>
    <div class="mt-2 w-full rounded-lg p-2 text-sm  bg-foreground/20">
        <div class="text-xs text-foreground/50 flex flex-row mb-2">
            <Wind color="#ccc" :size="16" />
            <span>风</span>
        </div>
        <div class="text-xs flex justify-between flex-row gap-2">
            <div class="w-1/2" v-if="curData">
                <div class="py-2 flex flex-row justify-between border-b-1 border-foreground/50">
                    <span>风力</span>
                    <!-- Generated by Copilot -->
                    <span class="text-foreground/50">{{ curData.wind.gust }}级</span>
                </div>
                <div class="py-2 flex flex-row justify-between border-b-1 border-foreground/50">
                    <span>阵风</span>
                    <span class="text-foreground/50">{{ curData.wind.speed }}米/秒</span>
                </div>
                <div class="py-2 flex flex-row justify-between">
                    <span>方向</span>
                    <span class="text-foreground/50">{{ getWindDirection(curData.wind.deg)
                        }}{{ curData.wind.deg }}°</span>
                </div>
            </div>
            <div class="w-1/2">
                <canvas id="wind-canvas" class="w-44"></canvas>
            </div>
        </div>
    </div>
</template>